apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vllm-llama-3-2-1b-instruct-daemonset
  namespace: datagen
spec:
  selector:
    matchLabels:
      app: vllm-llama-3-2-1b-instruct
  template:
    metadata:
      labels:
        app: vllm-llama-3-2-1b-instruct
    spec:
      containers:
      - args:
        - --model
        - meta-llama/Llama-3.2-1B-Instruct
        - --tensor-parallel-size
        - '1'
        - --pipeline-parallel-size
        - '1'
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugging-face-secrets
              key: HUGGING_FACE_HUB_TOKEN
        image: vllm/vllm-openai:latest
        name: vllm
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: '1'
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists