apiVersion: v1
kind: Service
metadata:
  name: vllm-llama-3-2-1b-instruct-service
  namespace: datagen
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: vllm-llama-3-2-1b-instruct